"""A setuptools based setup module.
See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""

from setuptools import setup, find_packages, Extension
from pathlib import Path
from distutils.command.build_ext import build_ext
from distutils.sysconfig import customize_compiler

include_dir = Path(".") / "pyradiohead_rf95" / "_extensions"
cpp_sources = list(
    map(str, (Path(".") / "pyradiohead_rf95" / "_extensions").glob("**/*.cpp"))
)

radiohead_module = Extension(
    "libradiohead",
    define_macros=[("RASPBERRY_PI", None), ("BCM2835_NO_DELAY_COMPATIBILITY", None)],
    include_dirs=["/usr/local/include", include_dir],
    libraries=["bcm2835"],
    sources=cpp_sources,
    optional=True
)


class my_build_ext(build_ext):
    def build_extensions(self):
        customize_compiler(self.compiler)
        try:
            self.compiler.compiler_so.remove("-Wstrict-prototypes")
            self.compiler.compiler_so.remove("-Werror=format-security")
        except (AttributeError, ValueError):
            pass
        build_ext.build_extensions(self)


setup(
    name="pyradiohead-rf95",
    version="0.1.0",
    description="",
    long_description_content_type="text/markdown",
    author="Nicolas Cellier",
    author_email="eryole@gmail.com",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
    ],  # Optional
    zip_safe=False,
    packages=find_packages(),
    setup_requires=["cffi>=1.0.0"],
    install_requires=["cffi>=1.0.0"],
    ext_package='pyradiohead_rf95',
    ext_modules=[radiohead_module],
    include_package_data=True,
    cmdclass={"build_ext": my_build_ext},
)
